### ISSUE TITLE
reverse-geocoding-0.1.0.1 fails Haddock phase

### ISSUE THREAD

**Issue by peti** [jcristovao/reverse-geocoding#1]
Haddock cannot process your source code, apparently because of some syntaxerror in the markup. At http://hydra.cryp.to/build/418515/nixlog/2/raw, you'll find a complete build log that shows the error message.

**Comment by jcristovao** [comment]
Hi... I had actually fixed this on a previous commit, but then I got distracted when I merged another branch and this creeped back in.

It should now be fixed, at least running cabal haddock in my system does not report errors.

I've pushed it here and to hackage, thanks!

**Comment by peti** [comment]
Very cool, thank you!

**Comment by peti** [comment]
Well, version 0.1.1.0 has exactly the same problem: 

```
src/Data/Geolocation/Reverse/Providers.hs:12:19:
    parse error on input ‘-- ^ Only one supported right now’
```

A complete build log is at http://hydra.cryp.to/build/525396/nixlog/1/raw.

**Comment by jcristovao** [comment]
Yes, my fault... it should be version 0.1.1.1: I uploaded the package candidate to hackage, forgot to publish.

Should be ok now, please confirm.

Cheers

**Comment by peti** [comment]
Works fine now: http://hydra.cryp.to/build/525788. Thank you!
